"""Document and Presentation Generator Module for Nexus.

Generates physical Word (.docx), PDF (.pdf), and PowerPoint (.pptx) files
from academic structured JSON content and automatically opens them on Windows.
"""

from datetime import datetime
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Any, Dict, List, Optional

# Primary designated save folder for generated assignments & presentations
DOCUMENTS_DIR = Path.home() / "Documents" / "Nexus" / "Generated_Documents"
PROJECT_DOCS_DIR = Path(__file__).resolve().parent.parent / "generated_documents"


def _ensure_output_dir() -> Path:
    """Ensures the destination output directory exists and returns the active path."""
    try:
        DOCUMENTS_DIR.mkdir(parents=True, exist_ok=True)
        return DOCUMENTS_DIR
    except Exception:
        PROJECT_DOCS_DIR.mkdir(parents=True, exist_ok=True)
        return PROJECT_DOCS_DIR


def _sanitize_filename(topic: str, extension: str) -> str:
    """Creates a safe, timestamped filename for the document."""
    clean_topic = re.sub(r"[^a-zA-Z0-9_\-\s]", "", topic).strip()
    clean_topic = re.sub(r"\s+", "_", clean_topic)
    if not clean_topic:
        clean_topic = "Assignment"
    clean_topic = clean_topic[:50]  # Limit length
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    ext = extension.lstrip(".")
    return f"{clean_topic}_{timestamp}.{ext}"


def open_generated_file(file_path: str) -> bool:
    """Opens the generated file with the user's default system application."""
    if not os.path.exists(file_path):
        print(f"[Document Generator: Warning] File not found to open: {file_path}")
        return False

    try:
        if hasattr(os, "startfile"):
            os.startfile(file_path)
            print(f"[Document Generator] Opened '{file_path}' with default system app via os.startfile.")
            return True
        elif sys.platform == "darwin":
            subprocess.Popen(["open", file_path])
            return True
        else:
            subprocess.Popen(["xdg-open", file_path])
            return True
    except Exception as err:
        print(f"[Document Generator: Error] Failed to open file '{file_path}': {err}")
        return False


def create_docx(content_data: Dict[str, Any], topic: str) -> str:
    """Generates a professional academic Word document (.docx) from structured JSON content."""
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = docx.Document()

    # Set standard page margins (1 inch)
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # Document Header / Title
    title_text = content_data.get("title", f"Academic Study on {topic}")
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(title_text)
    title_run.font.name = "Calibri"
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(26, 54, 93)  # Navy blue
    title_p.paragraph_format.space_after = Pt(4)

    # Subtitle
    subtitle_text = content_data.get("subtitle", f"An Undergraduate Assignment in {topic}")
    if subtitle_text:
        sub_p = doc.add_paragraph()
        sub_run = sub_p.add_run(subtitle_text)
        sub_run.font.name = "Calibri"
        sub_run.font.size = Pt(13)
        sub_run.font.italic = True
        sub_run.font.color.rgb = RGBColor(100, 116, 139)  # Slate gray
        sub_p.paragraph_format.space_after = Pt(12)

    # Metadata banner
    meta_p = doc.add_paragraph()
    meta_run = meta_p.add_run(f"Subject: {topic}  |  Generated by Nexus Academic Assistant  |  Date: {datetime.now().strftime('%B %d, %Y')}")
    meta_run.font.size = Pt(9.5)
    meta_run.font.color.rgb = RGBColor(148, 163, 184)
    meta_p.paragraph_format.space_after = Pt(18)

    # Abstract / Overview
    abstract_text = content_data.get("abstract", "")
    if abstract_text:
        abs_heading = doc.add_heading("Executive Summary / Abstract", level=2)
        abs_heading.paragraph_format.space_before = Pt(12)
        abs_heading.paragraph_format.space_after = Pt(6)

        abs_p = doc.add_paragraph()
        abs_run = abs_p.add_run(abstract_text)
        abs_run.font.name = "Calibri"
        abs_run.font.size = Pt(11)
        abs_run.font.italic = True
        abs_p.paragraph_format.space_after = Pt(14)

    # Sections
    sections = content_data.get("sections", [])
    for sec_idx, sec in enumerate(sections, 1):
        heading_text = sec.get("heading", f"Section {sec_idx}")
        sec_h = doc.add_heading(heading_text, level=1)
        sec_h.paragraph_format.space_before = Pt(16)
        sec_h.paragraph_format.space_after = Pt(6)

        subheading = sec.get("subheading", "")
        if subheading:
            sub_h = doc.add_heading(subheading, level=2)
            sub_h.paragraph_format.space_before = Pt(4)
            sub_h.paragraph_format.space_after = Pt(4)

        # Paragraphs
        paragraphs = sec.get("paragraphs", [])
        if isinstance(paragraphs, str):
            paragraphs = [paragraphs]
        for p_text in paragraphs:
            if not p_text:
                continue
            p = doc.add_paragraph()
            p_run = p.add_run(p_text)
            p_run.font.name = "Calibri"
            p_run.font.size = Pt(11)
            p.paragraph_format.line_spacing = 1.15
            p.paragraph_format.space_after = Pt(8)

        # Key takeaways
        takeaways = sec.get("key_takeaways", [])
        if takeaways:
            t_label = doc.add_paragraph()
            t_label_run = t_label.add_run("Key Takeaways:")
            t_label_run.font.bold = True
            t_label_run.font.size = Pt(10.5)
            t_label.paragraph_format.space_before = Pt(4)
            t_label.paragraph_format.space_after = Pt(2)

            for item in takeaways:
                t_p = doc.add_paragraph(style="List Bullet")
                t_run = t_p.add_run(item)
                t_run.font.size = Pt(10.5)
                t_p.paragraph_format.space_after = Pt(2)

    # Conclusion
    conclusion_text = content_data.get("conclusion", "")
    if conclusion_text:
        concl_h = doc.add_heading("Conclusion & Final Remarks", level=1)
        concl_h.paragraph_format.space_before = Pt(18)
        concl_h.paragraph_format.space_after = Pt(6)

        concl_p = doc.add_paragraph()
        concl_run = concl_p.add_run(conclusion_text)
        concl_run.font.name = "Calibri"
        concl_run.font.size = Pt(11)
        concl_p.paragraph_format.line_spacing = 1.15
        concl_p.paragraph_format.space_after = Pt(14)

    # References
    references = content_data.get("references", [])
    if references:
        ref_h = doc.add_heading("References & Recommended Reading", level=1)
        ref_h.paragraph_format.space_before = Pt(18)
        ref_h.paragraph_format.space_after = Pt(6)

        for ref in references:
            ref_p = doc.add_paragraph(style="List Bullet")
            ref_run = ref_p.add_run(ref)
            ref_run.font.size = Pt(10)
            ref_p.paragraph_format.space_after = Pt(3)

    out_dir = _ensure_output_dir()
    filename = _sanitize_filename(topic, "docx")
    file_path = str(out_dir / filename)
    doc.save(file_path)
    print(f"[Document Generator] DOCX successfully saved: {file_path}")
    return file_path


def create_pdf(content_data: Dict[str, Any], topic: str) -> str:
    """Generates a clean, formatted academic PDF document from structured JSON content."""
    from fpdf import FPDF

    class AcademicPDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(self.epw, 8, "Nexus Academic Assignment Document", align="R", new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(self.epw, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    pdf = AcademicPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.alias_nb_pages()
    pdf.add_page()

    def sanitize_text(text: str) -> str:
        """Sanitizes text for standard Latin-1 PDF output in FPDF."""
        if not text:
            return ""
        # Replace common unicode quotes and dashes with ASCII equivalents
        replacements = {
            "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
            "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2022": "*",
            "\u00a0": " ", "\u2192": "->", "\u2264": "<=", "\u2265": ">="
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        # Encode and ignore unencodable characters
        return text.encode("latin-1", "replace").decode("latin-1")

    # Title
    title = sanitize_text(content_data.get("title", f"Academic Study on {topic}"))
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(26, 54, 93)  # Navy
    pdf.multi_cell(pdf.epw, 9, title, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Subtitle
    subtitle = sanitize_text(content_data.get("subtitle", f"Undergraduate Assignment - {topic}"))
    if subtitle:
        pdf.set_font("Helvetica", "I", 12)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(pdf.epw, 6, subtitle, align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # Meta banner
    meta = sanitize_text(f"Subject: {topic} | Date: {datetime.now().strftime('%B %d, %Y')}")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(pdf.epw, 5, meta, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Abstract
    abstract = sanitize_text(content_data.get("abstract", ""))
    if abstract:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(pdf.epw, 7, "Executive Summary / Abstract", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(pdf.epw, 5.5, abstract, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Sections
    sections = content_data.get("sections", [])
    for sec_idx, sec in enumerate(sections, 1):
        heading = sanitize_text(sec.get("heading", f"Section {sec_idx}"))
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(pdf.epw, 8, heading, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        subheading = sanitize_text(sec.get("subheading", ""))
        if subheading:
            pdf.set_font("Helvetica", "B", 10.5)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(pdf.epw, 6, subheading, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

        paragraphs = sec.get("paragraphs", [])
        if isinstance(paragraphs, str):
            paragraphs = [paragraphs]
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        for p in paragraphs:
            if p:
                pdf.multi_cell(pdf.epw, 5.5, sanitize_text(p), new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2.5)

        takeaways = sec.get("key_takeaways", [])
        if takeaways:
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(pdf.epw, 5, "Key Takeaways:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9.5)
            for item in takeaways:
                pdf.multi_cell(pdf.epw, 5, f"  * {sanitize_text(item)}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2.5)

    # Conclusion
    conclusion = sanitize_text(content_data.get("conclusion", ""))
    if conclusion:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(pdf.epw, 8, "Conclusion & Final Remarks", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        pdf.multi_cell(pdf.epw, 5.5, conclusion, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # References
    references = content_data.get("references", [])
    if references:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(pdf.epw, 8, "References & Recommended Reading", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(71, 85, 105)
        for ref in references:
            pdf.multi_cell(pdf.epw, 4.5, f"  * {sanitize_text(ref)}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    out_dir = _ensure_output_dir()
    filename = _sanitize_filename(topic, "pdf")
    file_path = str(out_dir / filename)
    pdf.output(file_path)
    print(f"[Document Generator] PDF successfully saved: {file_path}")
    return file_path


def create_pptx(content_data: Dict[str, Any], topic: str) -> str:
    """Generates a clean academic PowerPoint presentation (.pptx) with concise bullets and detailed speaker notes."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    prs = Presentation()
    # Set slide dimensions to 16:9 widescreen (13.33 x 7.5 inches)
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]  # Blank slide for custom layout control

    # Slide 1: Title Slide
    title_slide = prs.slides.add_slide(blank_layout)

    # Title text box
    tb = title_slide.shapes.add_textbox(Inches(1.0), Inches(2.0), Inches(11.333), Inches(3.0))
    tf = tb.text_frame
    tf.word_wrap = True

    title_p = tf.paragraphs[0]
    title_p.text = content_data.get("title", f"Presentation on {topic}")
    title_p.font.size = Pt(36)
    title_p.font.bold = True
    title_p.font.color.rgb = RGBColor(26, 54, 93)

    subtitle_text = content_data.get("subtitle", f"Academic Lecture & Topic Analysis - {topic}")
    sub_p = tf.add_paragraph()
    sub_p.text = subtitle_text
    sub_p.font.size = Pt(20)
    sub_p.font.italic = True
    sub_p.font.color.rgb = RGBColor(100, 116, 139)
    sub_p.space_before = Pt(14)

    meta_p = tf.add_paragraph()
    meta_p.text = f"Target Audience: {content_data.get('target_audience', 'Undergraduate Level')}  |  Date: {datetime.now().strftime('%B %d, %Y')}"
    meta_p.font.size = Pt(14)
    meta_p.font.color.rgb = RGBColor(148, 163, 184)
    meta_p.space_before = Pt(14)

    # Slides
    slides_data = content_data.get("slides", [])
    for idx, s_data in enumerate(slides_data, 1):
        slide = prs.slides.add_slide(blank_layout)

        # Slide Heading
        heading_text = s_data.get("heading", f"Slide {idx}")
        h_box = slide.shapes.add_textbox(Inches(1.0), Inches(0.8), Inches(11.333), Inches(1.0))
        h_tf = h_box.text_frame
        h_tf.word_wrap = True
        h_p = h_tf.paragraphs[0]
        h_p.text = heading_text
        h_p.font.size = Pt(28)
        h_p.font.bold = True
        h_p.font.color.rgb = RGBColor(26, 54, 93)

        # Bullets Body
        bullets = s_data.get("bullets", [])
        if bullets:
            b_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.0), Inches(11.333), Inches(4.5))
            b_tf = b_box.text_frame
            b_tf.word_wrap = True

            for b_idx, bullet_item in enumerate(bullets):
                b_p = b_tf.paragraphs[0] if b_idx == 0 else b_tf.add_paragraph()
                b_p.text = f"•  {bullet_item}"
                b_p.font.size = Pt(18)
                b_p.font.color.rgb = RGBColor(30, 41, 59)
                b_p.space_after = Pt(14)

        # Speaker Notes
        speaker_notes = s_data.get("speaker_notes", "")
        if speaker_notes:
            notes_slide = slide.notes_slide
            notes_tf = notes_slide.notes_text_frame
            notes_tf.text = speaker_notes

    # Summary Slide
    summary_data = content_data.get("summary_slide", {})
    if summary_data:
        sum_slide = prs.slides.add_slide(blank_layout)

        sum_h_box = sum_slide.shapes.add_textbox(Inches(1.0), Inches(0.8), Inches(11.333), Inches(1.0))
        sum_h_tf = sum_h_box.text_frame
        sum_h_tf.word_wrap = True
        sum_h_p = sum_h_tf.paragraphs[0]
        sum_h_p.text = summary_data.get("heading", "Conclusion & Key Takeaways")
        sum_h_p.font.size = Pt(28)
        sum_h_p.font.bold = True
        sum_h_p.font.color.rgb = RGBColor(26, 54, 93)

        sum_bullets = summary_data.get("bullets", [])
        if sum_bullets:
            sum_b_box = sum_slide.shapes.add_textbox(Inches(1.0), Inches(2.0), Inches(11.333), Inches(4.5))
            sum_b_tf = sum_b_box.text_frame
            sum_b_tf.word_wrap = True

            for b_idx, bullet_item in enumerate(sum_bullets):
                b_p = sum_b_tf.paragraphs[0] if b_idx == 0 else sum_b_tf.add_paragraph()
                b_p.text = f"•  {bullet_item}"
                b_p.font.size = Pt(18)
                b_p.font.color.rgb = RGBColor(30, 41, 59)
                b_p.space_after = Pt(14)

        sum_notes = summary_data.get("speaker_notes", "")
        if sum_notes:
            sum_notes_slide = sum_slide.notes_slide
            sum_notes_tf = sum_notes_slide.notes_text_frame
            sum_notes_tf.text = sum_notes

    out_dir = _ensure_output_dir()
    filename = _sanitize_filename(topic, "pptx")
    file_path = str(out_dir / filename)
    prs.save(file_path)
    print(f"[Document Generator] PPTX successfully saved: {file_path}")
    return file_path


def create_assignment_document(topic: str, doc_type: str = "docx") -> str:
    """Master workflow: generates detailed academic JSON content, creates the physical file, and opens it.

    Args:
        topic (str): The subject or topic of the assignment (e.g. 'Photosynthesis', 'French Revolution').
        doc_type (str): Output format ('docx', 'pdf', 'pptx'). Default is 'docx'.

    Returns:
        str: Confirmation message for Nexus to speak to the user.
    """
    from modules.gemini_client import generate_document_content

    normalized_type = doc_type.strip().lower()
    if "pdf" in normalized_type:
        fmt = "pdf"
        fmt_name = "PDF Document"
    elif any(k in normalized_type for k in ["ppt", "presentation", "slide", "powerpoint"]):
        fmt = "pptx"
        fmt_name = "PowerPoint Presentation"
    else:
        fmt = "docx"
        fmt_name = "Word Document"

    print(f"[create_assignment_document] Initiating creation of {fmt_name} for topic: '{topic}'...")

    # Step 1: Generate rich academic structured content via Gemini
    content_data = generate_document_content(topic=topic, doc_type=fmt)
    if not content_data or not isinstance(content_data, dict):
        return f"Sorry, I encountered an issue generating the academic content for {topic}."

    # Step 2: Render physical file based on format
    try:
        if fmt == "docx":
            file_path = create_docx(content_data, topic)
        elif fmt == "pdf":
            file_path = create_pdf(content_data, topic)
        elif fmt == "pptx":
            file_path = create_pptx(content_data, topic)
        else:
            file_path = create_docx(content_data, topic)

        # Step 3: Open file with default application
        open_generated_file(file_path)

        filename = os.path.basename(file_path)
        return f"Your {fmt_name} on '{topic}' is ready and open ({filename})."

    except Exception as err:
        print(f"[create_assignment_document: Error] File generation failed: {err}")
        return f"An error occurred while creating your {fmt_name}: {err}"


__all__ = [
    "create_assignment_document",
    "create_docx",
    "create_pdf",
    "create_pptx",
    "open_generated_file",
]
